theme: jekyll-theme-minimal
title: Rajesh Krishnan
description: Namaste (नमस्ते). Welcome to my web site. I am a retired computer scientist who lives in Fort Valley, Virginia, USA. 
permalink: pretty
